"use client";

import React, { createContext, useContext, useMemo, useState } from "react";
import { Device, DeviceBrand } from "./types";

// BASE DE DATOS MAESTRA COMPLETA (YAMMIR FF - 2026)
const RAW_DEVICES: Record<string, Device[]> = {
  samsung: [
    {
      name: "Galaxy S25 Ultra",
      dpi: 505,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 480,
      display_type: "Dynamic AMOLED 2X",
      ui: "One UI 7",
      screen_size_inches: 6.8,
    },
    {
      name: "Galaxy S25+",
      dpi: 500,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 480,
      display_type: "Dynamic AMOLED 2X",
      ui: "One UI 7",
      screen_size_inches: 6.7,
    },
    {
      name: "Galaxy S25",
      dpi: 480,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 480,
      display_type: "Dynamic AMOLED 2X",
      ui: "One UI 7",
      screen_size_inches: 6.2,
    },
    {
      name: "Galaxy S24 Ultra",
      dpi: 505,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Dynamic AMOLED 2X",
      ui: "One UI 6.1",
      screen_size_inches: 6.8,
    },
    {
      name: "Galaxy S24+",
      dpi: 500,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Dynamic AMOLED 2X",
      ui: "One UI 6.1",
      screen_size_inches: 6.7,
    },
    {
      name: "Galaxy S24",
      dpi: 480,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Dynamic AMOLED 2X",
      ui: "One UI 6.1",
      screen_size_inches: 6.2,
    },
    {
      name: "Galaxy S24 FE",
      dpi: 401,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Dynamic AMOLED",
      ui: "One UI 6.1",
      screen_size_inches: 6.4,
    },
    {
      name: "Galaxy S23 Ultra",
      dpi: 501,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Dynamic AMOLED 2X",
      ui: "One UI 6",
      screen_size_inches: 6.8,
    },
    {
      name: "Galaxy S23+",
      dpi: 393,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Dynamic AMOLED 2X",
      ui: "One UI 6",
      screen_size_inches: 6.6,
    },
    {
      name: "Galaxy S23",
      dpi: 425,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Dynamic AMOLED 2X",
      ui: "One UI 6",
      screen_size_inches: 6.1,
    },
    {
      name: "Galaxy S23 FE",
      dpi: 401,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Dynamic AMOLED",
      ui: "One UI 6",
      screen_size_inches: 6.4,
    },
    {
      name: "Galaxy S22 Ultra",
      dpi: 500,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Dynamic AMOLED 2X",
      ui: "One UI 5",
      screen_size_inches: 6.8,
    },
    {
      name: "Galaxy S22+",
      dpi: 393,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Dynamic AMOLED 2X",
      ui: "One UI 5",
      screen_size_inches: 6.6,
    },
    {
      name: "Galaxy S22",
      dpi: 425,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Dynamic AMOLED 2X",
      ui: "One UI 5",
      screen_size_inches: 6.1,
    },
    {
      name: "Galaxy S22 FE",
      dpi: 401,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Dynamic AMOLED",
      ui: "One UI 5",
      screen_size_inches: 6.4,
    },
    {
      name: "Galaxy S21 Ultra",
      dpi: 515,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Dynamic AMOLED 2X",
      ui: "One UI 4",
      screen_size_inches: 6.8,
    },
    {
      name: "Galaxy S21+",
      dpi: 394,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Dynamic AMOLED 2X",
      ui: "One UI 4",
      screen_size_inches: 6.7,
    },
    {
      name: "Galaxy S21",
      dpi: 421,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Dynamic AMOLED 2X",
      ui: "One UI 4",
      screen_size_inches: 6.2,
    },
    {
      name: "Galaxy S21 FE",
      dpi: 401,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Dynamic AMOLED",
      ui: "One UI 4",
      screen_size_inches: 6.4,
    },
    {
      name: "Galaxy S20 Ultra",
      dpi: 511,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Dynamic AMOLED 2X",
      ui: "One UI 3",
      screen_size_inches: 6.9,
    },
    {
      name: "Galaxy S20+",
      dpi: 525,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Dynamic AMOLED 2X",
      ui: "One UI 3",
      screen_size_inches: 6.7,
    },
    {
      name: "Galaxy S20",
      dpi: 563,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Dynamic AMOLED 2X",
      ui: "One UI 3",
      screen_size_inches: 6.2,
    },
    {
      name: "Galaxy Z Fold 6",
      dpi: 402,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Dynamic AMOLED 2X",
      ui: "One UI 6.1",
      screen_size_inches: 7.6,
    },
    {
      name: "Galaxy Z Flip 6",
      dpi: 426,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Dynamic AMOLED 2X",
      ui: "One UI 6.1",
      screen_size_inches: 6.7,
    },
    {
      name: "Galaxy Z Fold 5",
      dpi: 402,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Dynamic AMOLED 2X",
      ui: "One UI 6",
      screen_size_inches: 7.6,
    },
    {
      name: "Galaxy Z Flip 5",
      dpi: 426,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Dynamic AMOLED 2X",
      ui: "One UI 6",
      screen_size_inches: 6.7,
    },
    {
      name: "Galaxy Z Fold 4",
      dpi: 374,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Dynamic AMOLED 2X",
      ui: "One UI 5",
      screen_size_inches: 7.6,
    },
    {
      name: "Galaxy Z Flip 4",
      dpi: 425,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Dynamic AMOLED 2X",
      ui: "One UI 5",
      screen_size_inches: 6.7,
    },
    {
      name: "Galaxy Z Fold 3",
      dpi: 374,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Dynamic AMOLED 2X",
      ui: "One UI 4",
      screen_size_inches: 7.6,
    },
    {
      name: "Galaxy Z Flip 3",
      dpi: 426,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Dynamic AMOLED 2X",
      ui: "One UI 4",
      screen_size_inches: 6.7,
    },
    {
      name: "Galaxy Z Fold 2",
      dpi: 373,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Dynamic AMOLED 2X",
      ui: "One UI 3",
      screen_size_inches: 7.6,
    },
    {
      name: "Galaxy Z Flip 5G",
      dpi: 425,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Dynamic AMOLED",
      ui: "One UI 3",
      screen_size_inches: 6.7,
    },
    {
      name: "Galaxy A73",
      dpi: 393,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Super AMOLED",
      ui: "One UI 5.1",
      screen_size_inches: 6.7,
    },
    {
      name: "Galaxy A72",
      dpi: 393,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "Super AMOLED",
      ui: "One UI 3.1",
      screen_size_inches: 6.7,
    },
    {
      name: "Galaxy A55",
      dpi: 401,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Super AMOLED",
      ui: "One UI 6.1",
      screen_size_inches: 6.6,
    },
    {
      name: "Galaxy A54",
      dpi: 403,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Super AMOLED",
      ui: "One UI 5.1",
      screen_size_inches: 6.4,
    },
    {
      name: "Galaxy A53",
      dpi: 405,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Super AMOLED",
      ui: "One UI 4.1",
      screen_size_inches: 6.5,
    },
    {
      name: "Galaxy A52s",
      dpi: 405,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Super AMOLED",
      ui: "One UI 3",
      screen_size_inches: 6.5,
    },
    {
      name: "Galaxy A52",
      dpi: 407,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "Super AMOLED",
      ui: "One UI 3",
      screen_size_inches: 6.5,
    },
    {
      name: "Galaxy A35",
      dpi: 401,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Super AMOLED",
      ui: "One UI 6.1",
      screen_size_inches: 6.6,
    },
    {
      name: "Galaxy A34",
      dpi: 401,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Super AMOLED",
      ui: "One UI 5.1",
      screen_size_inches: 6.6,
    },
    {
      name: "Galaxy A33 5G",
      dpi: 411,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "Super AMOLED",
      ui: "One UI 4.1",
      screen_size_inches: 6.4,
    },
    {
      name: "Galaxy A32",
      dpi: 411,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "Super AMOLED",
      ui: "One UI 3",
      screen_size_inches: 6.4,
    },
    {
      name: "Galaxy A27",
      dpi: 401,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "Super AMOLED",
      ui: "One UI 6",
      screen_size_inches: 6.6,
    },
    {
      name: "Galaxy A26 5G",
      dpi: 396,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "LCD",
      ui: "One UI 5",
      screen_size_inches: 6.6,
    },
    {
      name: "Galaxy A25",
      dpi: 396,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "Super AMOLED",
      ui: "One UI 6",
      screen_size_inches: 6.5,
    },
    {
      name: "Galaxy A24",
      dpi: 396,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "Super AMOLED",
      ui: "One UI 5.1",
      screen_size_inches: 6.5,
    },
    {
      name: "Galaxy A23",
      dpi: 400,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "PLS LCD",
      ui: "One UI 4.1",
      screen_size_inches: 6.6,
    },
    {
      name: "Galaxy A22 5G",
      dpi: 399,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "TFT LCD",
      ui: "One UI 3.1",
      screen_size_inches: 6.6,
    },
    {
      name: "Galaxy A22",
      dpi: 274,
      tier: "low",
      hz: 60,
      touch_sampling_rate: 120,
      display_type: "Super AMOLED",
      ui: "One UI Core 3.1",
      screen_size_inches: 6.4,
    },
    {
      name: "Galaxy A21s",
      dpi: 266,
      tier: "low",
      hz: 60,
      touch_sampling_rate: 120,
      display_type: "PLS TFT",
      ui: "One UI 2",
      screen_size_inches: 6.5,
    },
    {
      name: "Galaxy A16 5G",
      dpi: 396,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "LCD",
      ui: "One UI 6",
      screen_size_inches: 6.6,
    },
    {
      name: "Galaxy A15",
      dpi: 396,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "Super AMOLED",
      ui: "One UI 6",
      screen_size_inches: 6.5,
    },
    {
      name: "Galaxy A14",
      dpi: 269,
      tier: "low",
      hz: 60,
      touch_sampling_rate: 120,
      display_type: "PLS LCD",
      ui: "One UI Core 5",
      screen_size_inches: 6.6,
    },
    {
      name: "Galaxy A13",
      dpi: 267,
      tier: "low",
      hz: 60,
      touch_sampling_rate: 120,
      display_type: "PLS TFT",
      ui: "One UI Core 3",
      screen_size_inches: 6.6,
    },
    {
      name: "Galaxy A12",
      dpi: 264,
      tier: "low",
      hz: 60,
      touch_sampling_rate: 120,
      display_type: "PLS TFT",
      ui: "One UI Core 3",
      screen_size_inches: 6.5,
    },
    {
      name: "Galaxy M55",
      dpi: 403,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Super AMOLED",
      ui: "One UI 6",
      screen_size_inches: 6.7,
    },
    {
      name: "Galaxy M54",
      dpi: 403,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Super AMOLED",
      ui: "One UI 5",
      screen_size_inches: 6.7,
    },
    {
      name: "Galaxy M53",
      dpi: 405,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Super AMOLED",
      ui: "One UI 4.1",
      screen_size_inches: 6.7,
    },
    {
      name: "Galaxy M52",
      dpi: 405,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Super AMOLED",
      ui: "One UI 3",
      screen_size_inches: 6.7,
    },
    {
      name: "Galaxy M35",
      dpi: 401,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "Super AMOLED",
      ui: "One UI 6",
      screen_size_inches: 6.6,
    },
    {
      name: "Galaxy M34",
      dpi: 401,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "Super AMOLED",
      ui: "One UI 5.1",
      screen_size_inches: 6.6,
    },
    {
      name: "Galaxy M33",
      dpi: 393,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "LCD",
      ui: "One UI 4.1",
      screen_size_inches: 6.6,
    },
    {
      name: "Galaxy M32",
      dpi: 401,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "Super AMOLED",
      ui: "One UI 3",
      screen_size_inches: 6.4,
    },
    {
      name: "Galaxy M23",
      dpi: 400,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "LCD",
      ui: "One UI 4.1",
      screen_size_inches: 6.6,
    },
    {
      name: "Galaxy M22",
      dpi: 274,
      tier: "low",
      hz: 60,
      touch_sampling_rate: 120,
      display_type: "Super AMOLED",
      ui: "One UI Core 3",
      screen_size_inches: 6.4,
    },
    {
      name: "Galaxy M16",
      dpi: 396,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "LCD",
      ui: "One UI 6",
      screen_size_inches: 6.6,
    },
    {
      name: "Galaxy F55",
      dpi: 403,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Super AMOLED",
      ui: "One UI 6",
      screen_size_inches: 6.7,
    },
    {
      name: "Galaxy F54",
      dpi: 403,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Super AMOLED",
      ui: "One UI 5.1",
      screen_size_inches: 6.7,
    },
    {
      name: "Galaxy F34",
      dpi: 401,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Super AMOLED",
      ui: "One UI 5.1",
      screen_size_inches: 6.5,
    },
    {
      name: "Galaxy Tab S9 Ultra",
      dpi: 240,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Dynamic AMOLED 2X",
      ui: "One UI 6",
      screen_size_inches: 14.6,
    },
    {
      name: "Galaxy Tab S9+",
      dpi: 266,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Dynamic AMOLED 2X",
      ui: "One UI 6",
      screen_size_inches: 12.4,
    },
    {
      name: "Galaxy Tab S8 Ultra",
      dpi: 240,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Super AMOLED",
      ui: "One UI 5",
      screen_size_inches: 14.6,
    },
    {
      name: "Otros Samsung",
      dpi: 400,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "AMOLED",
      ui: "One UI",
      screen_size_inches: 6.5,
    },
  ],
  apple: [
    {
      name: "iPhone 17 Pro Max",
      dpi: 460,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "LTPO Super Retina XDR OLED",
      ui: "iOS 19",
      screen_size_inches: 6.9,
    },
    {
      name: "iPhone 17 Pro",
      dpi: 460,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "LTPO Super Retina XDR OLED",
      ui: "iOS 19",
      screen_size_inches: 6.3,
    },
    {
      name: "iPhone 17 Air",
      dpi: 460,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "OLED",
      ui: "iOS 19",
      screen_size_inches: 6.3,
    },
    {
      name: "iPhone 17",
      dpi: 460,
      tier: "mid_high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "LTPO OLED",
      ui: "iOS 19",
      screen_size_inches: 6.1,
    },
    {
      name: "iPhone 16 Pro Max",
      dpi: 460,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "LTPO Super Retina XDR OLED",
      ui: "iOS 18",
      screen_size_inches: 6.9,
    },
    {
      name: "iPhone 16 Pro",
      dpi: 460,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "LTPO Super Retina XDR OLED",
      ui: "iOS 18",
      screen_size_inches: 6.3,
    },
    {
      name: "iPhone 16 Plus",
      dpi: 460,
      tier: "high",
      hz: 60,
      touch_sampling_rate: 120,
      display_type: "Super Retina XDR OLED",
      ui: "iOS 18",
      screen_size_inches: 6.7,
    },
    {
      name: "iPhone 16",
      dpi: 460,
      tier: "high",
      hz: 60,
      touch_sampling_rate: 120,
      display_type: "Super Retina XDR OLED",
      ui: "iOS 18",
      screen_size_inches: 6.1,
    },
    {
      name: "iPhone 15 Pro Max",
      dpi: 460,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "LTPO Super Retina XDR OLED",
      ui: "iOS 17",
      screen_size_inches: 6.7,
    },
    {
      name: "iPhone 15 Pro",
      dpi: 460,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "LTPO Super Retina XDR OLED",
      ui: "iOS 17",
      screen_size_inches: 6.1,
    },
    {
      name: "iPhone 15 Plus",
      dpi: 460,
      tier: "high",
      hz: 60,
      touch_sampling_rate: 120,
      display_type: "Super Retina XDR OLED",
      ui: "iOS 17",
      screen_size_inches: 6.7,
    },
    {
      name: "iPhone 15",
      dpi: 460,
      tier: "high",
      hz: 60,
      touch_sampling_rate: 120,
      display_type: "Super Retina XDR OLED",
      ui: "iOS 17",
      screen_size_inches: 6.1,
    },
    {
      name: "iPhone 14 Pro Max",
      dpi: 460,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "LTPO Super Retina XDR OLED",
      ui: "iOS 16",
      screen_size_inches: 6.7,
    },
    {
      name: "iPhone 14 Pro",
      dpi: 460,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "LTPO Super Retina XDR OLED",
      ui: "iOS 16",
      screen_size_inches: 6.1,
    },
    {
      name: "iPhone 14 Plus",
      dpi: 458,
      tier: "high",
      hz: 60,
      touch_sampling_rate: 120,
      display_type: "Super Retina XDR OLED",
      ui: "iOS 16",
      screen_size_inches: 6.7,
    },
    {
      name: "iPhone 14",
      dpi: 460,
      tier: "high",
      hz: 60,
      touch_sampling_rate: 120,
      display_type: "Super Retina XDR OLED",
      ui: "iOS 16",
      screen_size_inches: 6.1,
    },
    {
      name: "iPhone 13 Pro Max",
      dpi: 458,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "LTPO Super Retina XDR OLED",
      ui: "iOS 15",
      screen_size_inches: 6.7,
    },
    {
      name: "iPhone 13 Pro",
      dpi: 460,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "LTPO Super Retina XDR OLED",
      ui: "iOS 15",
      screen_size_inches: 6.1,
    },
    {
      name: "iPhone 13",
      dpi: 460,
      tier: "high",
      hz: 60,
      touch_sampling_rate: 120,
      display_type: "Super Retina XDR OLED",
      ui: "iOS 15",
      screen_size_inches: 6.1,
    },
    {
      name: "iPhone 13 mini",
      dpi: 476,
      tier: "high",
      hz: 60,
      touch_sampling_rate: 120,
      display_type: "Super Retina XDR OLED",
      ui: "iOS 15",
      screen_size_inches: 5.4,
    },
    {
      name: "iPhone 12 Pro Max",
      dpi: 458,
      tier: "high",
      hz: 60,
      touch_sampling_rate: 120,
      display_type: "Super Retina XDR OLED",
      ui: "iOS 14",
      screen_size_inches: 6.7,
    },
    {
      name: "iPhone 12 Pro",
      dpi: 460,
      tier: "high",
      hz: 60,
      touch_sampling_rate: 120,
      display_type: "Super Retina XDR OLED",
      ui: "iOS 14",
      screen_size_inches: 6.1,
    },
    {
      name: "iPhone 12",
      dpi: 460,
      tier: "high",
      hz: 60,
      touch_sampling_rate: 120,
      display_type: "Super Retina XDR OLED",
      ui: "iOS 14",
      screen_size_inches: 6.1,
    },
    {
      name: "iPhone 11 Pro Max",
      dpi: 458,
      tier: "high",
      hz: 60,
      touch_sampling_rate: 120,
      display_type: "Super Retina XDR OLED",
      ui: "iOS 13",
      screen_size_inches: 6.5,
    },
    {
      name: "iPhone 11",
      dpi: 326,
      tier: "mid",
      hz: 60,
      touch_sampling_rate: 120,
      display_type: "Liquid Retina IPS LCD",
      ui: "iOS 13",
      screen_size_inches: 6.1,
    },
    {
      name: "iPhone SE (2022)",
      dpi: 326,
      tier: "mid",
      hz: 60,
      touch_sampling_rate: 120,
      display_type: "Retina IPS LCD",
      ui: "iOS 15",
      screen_size_inches: 4.7,
    },
    {
      name: "Otros iPhone",
      dpi: 460,
      tier: "high",
      hz: 60,
      touch_sampling_rate: 120,
      display_type: "Super Retina XDR OLED",
      ui: "iOS",
      screen_size_inches: 6.1,
    },
  ],
  xiaomi: [
    {
      name: "Xiaomi 15 Ultra",
      dpi: 522,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 480,
      display_type: "AMOLED",
      ui: "HyperOS",
      screen_size_inches: 6.73,
    },
    {
      name: "Xiaomi 15 Pro",
      dpi: 522,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 480,
      display_type: "AMOLED",
      ui: "HyperOS",
      screen_size_inches: 6.73,
    },
    {
      name: "Xiaomi 15",
      dpi: 460,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 480,
      display_type: "AMOLED",
      ui: "HyperOS",
      screen_size_inches: 6.36,
    },
    {
      name: "Xiaomi 14 Ultra",
      dpi: 522,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "LTPO AMOLED",
      ui: "HyperOS",
      screen_size_inches: 6.73,
    },
    {
      name: "Xiaomi 14 Pro",
      dpi: 522,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "LTPO AMOLED",
      ui: "HyperOS",
      screen_size_inches: 6.73,
    },
    {
      name: "Xiaomi 14",
      dpi: 460,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "LTPO AMOLED",
      ui: "HyperOS",
      screen_size_inches: 6.36,
    },
    {
      name: "Xiaomi 14T Pro",
      dpi: 446,
      tier: "high",
      hz: 144,
      touch_sampling_rate: 480,
      display_type: "AMOLED",
      ui: "HyperOS",
      screen_size_inches: 6.67,
    },
    {
      name: "Xiaomi 14T",
      dpi: 395,
      tier: "high",
      hz: 144,
      touch_sampling_rate: 480,
      display_type: "AMOLED",
      ui: "HyperOS",
      screen_size_inches: 6.67,
    },
    {
      name: "Xiaomi 13 Ultra",
      dpi: 522,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "LTPO AMOLED",
      ui: "MIUI 14",
      screen_size_inches: 6.73,
    },
    {
      name: "Xiaomi 13 Pro",
      dpi: 521,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "LTPO AMOLED",
      ui: "MIUI 14",
      screen_size_inches: 6.73,
    },
    {
      name: "Xiaomi 13",
      dpi: 414,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "MIUI 14",
      screen_size_inches: 6.36,
    },
    {
      name: "Xiaomi 12 Pro",
      dpi: 521,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 480,
      display_type: "LTPO AMOLED",
      ui: "MIUI 13",
      screen_size_inches: 6.73,
    },
    {
      name: "Xiaomi 12",
      dpi: 419,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 480,
      display_type: "AMOLED",
      ui: "MIUI 13",
      screen_size_inches: 6.28,
    },
    {
      name: "Redmi Note 14 Pro+",
      dpi: 446,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 216,
      display_type: "AMOLED",
      ui: "HyperOS",
      screen_size_inches: 6.67,
    },
    {
      name: "Redmi Note 14 Pro",
      dpi: 395,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 216,
      display_type: "AMOLED",
      ui: "HyperOS",
      screen_size_inches: 6.67,
    },
    {
      name: "Redmi Note 14",
      dpi: 395,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "IPS LCD",
      ui: "HyperOS",
      screen_size_inches: 6.72,
    },
    {
      name: "Redmi Note 13 Pro+",
      dpi: 446,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 216,
      display_type: "AMOLED",
      ui: "MIUI 14",
      screen_size_inches: 6.67,
    },
    {
      name: "Redmi Note 13 Pro",
      dpi: 395,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 216,
      display_type: "AMOLED",
      ui: "MIUI 14",
      screen_size_inches: 6.67,
    },
    {
      name: "Redmi Note 13",
      dpi: 395,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "IPS LCD",
      ui: "MIUI 14",
      screen_size_inches: 6.67,
    },
    {
      name: "Redmi Note 12 Pro+",
      dpi: 395,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "MIUI 13",
      screen_size_inches: 6.67,
    },
    {
      name: "Redmi Note 12 Pro",
      dpi: 395,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "MIUI 13",
      screen_size_inches: 6.67,
    },
    {
      name: "Redmi Note 11 Pro+",
      dpi: 395,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "MIUI 13",
      screen_size_inches: 6.67,
    },
    {
      name: "Redmi Note 11",
      dpi: 409,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "AMOLED",
      ui: "MIUI 13",
      screen_size_inches: 6.43,
    },
    {
      name: "Redmi 14C",
      dpi: 269,
      tier: "low",
      hz: 60,
      touch_sampling_rate: 120,
      display_type: "IPS LCD",
      ui: "HyperOS",
      screen_size_inches: 6.74,
    },
    {
      name: "Redmi 13C",
      dpi: 269,
      tier: "low",
      hz: 60,
      touch_sampling_rate: 120,
      display_type: "IPS LCD",
      ui: "MIUI 14",
      screen_size_inches: 6.74,
    },
    {
      name: "Redmi 12",
      dpi: 395,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "IPS LCD",
      ui: "MIUI 14",
      screen_size_inches: 6.79,
    },
    {
      name: "Otros Xiaomi",
      dpi: 400,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "AMOLED",
      ui: "HyperOS",
      screen_size_inches: 6.6,
    },
  ],
  poco: [
    {
      name: "Poco X7 Pro",
      dpi: 446,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 216,
      display_type: "AMOLED",
      ui: "HyperOS",
      screen_size_inches: 6.67,
    },
    {
      name: "Poco X7",
      dpi: 395,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "IPS LCD",
      ui: "HyperOS",
      screen_size_inches: 6.67,
    },
    {
      name: "Poco X6 Pro",
      dpi: 446,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "HyperOS",
      screen_size_inches: 6.67,
    },
    {
      name: "Poco X6",
      dpi: 395,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "IPS LCD",
      ui: "HyperOS",
      screen_size_inches: 6.67,
    },
    {
      name: "Poco X5 Pro",
      dpi: 395,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "MIUI 14",
      screen_size_inches: 6.67,
    },
    {
      name: "Poco X4 Pro 5G",
      dpi: 395,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 360,
      display_type: "AMOLED",
      ui: "MIUI 13",
      screen_size_inches: 6.67,
    },
    {
      name: "Poco F6 Pro",
      dpi: 526,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 480,
      display_type: "AMOLED",
      ui: "HyperOS",
      screen_size_inches: 6.67,
    },
    {
      name: "Poco F6",
      dpi: 395,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "HyperOS",
      screen_size_inches: 6.67,
    },
    {
      name: "Poco F5 Pro",
      dpi: 526,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 480,
      display_type: "AMOLED",
      ui: "MIUI 14",
      screen_size_inches: 6.67,
    },
    {
      name: "Poco F4 GT",
      dpi: 395,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 480,
      display_type: "AMOLED",
      ui: "MIUI 13",
      screen_size_inches: 6.67,
    },
    {
      name: "Poco F3",
      dpi: 395,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 360,
      display_type: "AMOLED",
      ui: "MIUI 12",
      screen_size_inches: 6.67,
    },
    {
      name: "Poco M6 Pro",
      dpi: 395,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "IPS LCD",
      ui: "MIUI 14",
      screen_size_inches: 6.79,
    },
    {
      name: "Poco M5",
      dpi: 401,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "IPS LCD",
      ui: "MIUI 13",
      screen_size_inches: 6.58,
    },
    {
      name: "Poco C65",
      dpi: 269,
      tier: "low",
      hz: 60,
      touch_sampling_rate: 180,
      display_type: "IPS LCD",
      ui: "MIUI 14",
      screen_size_inches: 6.74,
    },
    {
      name: "Otros Poco",
      dpi: 400,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "AMOLED",
      ui: "HyperOS",
      screen_size_inches: 6.6,
    },
  ],
  huawei: [
    {
      name: "Mate 70 Pro+",
      dpi: 460,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 360,
      display_type: "LTPO OLED",
      ui: "HarmonyOS 5",
      screen_size_inches: 6.8,
    },
    {
      name: "Mate 70",
      dpi: 452,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 300,
      display_type: "OLED",
      ui: "HarmonyOS 5",
      screen_size_inches: 6.7,
    },
    {
      name: "Mate 60 Pro",
      dpi: 460,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 360,
      display_type: "LTPO OLED",
      ui: "HarmonyOS 4",
      screen_size_inches: 6.82,
    },
    {
      name: "Mate X5",
      dpi: 426,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Foldable LTPO OLED",
      ui: "HarmonyOS 4",
      screen_size_inches: 7.85,
    },
    {
      name: "Pura 70 Ultra",
      dpi: 460,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 360,
      display_type: "LTPO OLED",
      ui: "HarmonyOS 4",
      screen_size_inches: 6.8,
    },
    {
      name: "P60 Pro",
      dpi: 460,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 300,
      display_type: "LTPO OLED",
      ui: "HarmonyOS 3",
      screen_size_inches: 6.67,
    },
    {
      name: "Nova 13 Pro",
      dpi: 440,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 300,
      display_type: "OLED",
      ui: "HarmonyOS 4",
      screen_size_inches: 6.76,
    },
    {
      name: "Nova 12",
      dpi: 440,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 300,
      display_type: "OLED",
      ui: "HarmonyOS 4",
      screen_size_inches: 6.7,
    },
    {
      name: "Nova 11 Pro",
      dpi: 440,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 300,
      display_type: "OLED",
      ui: "HarmonyOS 3",
      screen_size_inches: 6.78,
    },
    {
      name: "Y9a",
      dpi: 391,
      tier: "low",
      hz: 60,
      touch_sampling_rate: 180,
      display_type: "IPS LCD",
      ui: "EMUI 10.1",
      screen_size_inches: 6.63,
    },
    {
      name: "Otros Huawei",
      dpi: 400,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 240,
      display_type: "OLED",
      ui: "HarmonyOS",
      screen_size_inches: 6.6,
    },
  ],
  honor: [
    {
      name: "Magic 7 Pro",
      dpi: 460,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 360,
      display_type: "LTPO AMOLED",
      ui: "MagicOS 9",
      screen_size_inches: 6.8,
    },
    {
      name: "Magic 6 Pro",
      dpi: 460,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 360,
      display_type: "LTPO AMOLED",
      ui: "MagicOS 8",
      screen_size_inches: 6.8,
    },
    {
      name: "Magic 5 Pro",
      dpi: 461,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 360,
      display_type: "LTPO OLED",
      ui: "MagicOS 7.1",
      screen_size_inches: 6.81,
    },
    {
      name: "Magic V3",
      dpi: 393,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "Foldable LTPO OLED",
      ui: "MagicOS 8",
      screen_size_inches: 7.9,
    },
    {
      name: "Honor 200 Pro",
      dpi: 446,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 300,
      display_type: "OLED",
      ui: "MagicOS 8",
      screen_size_inches: 6.78,
    },
    {
      name: "Honor 100",
      dpi: 435,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 300,
      display_type: "OLED",
      ui: "MagicOS 7.2",
      screen_size_inches: 6.7,
    },
    {
      name: "Honor 90",
      dpi: 435,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 300,
      display_type: "OLED",
      ui: "MagicOS 7.1",
      screen_size_inches: 6.7,
    },
    {
      name: "Honor X9b",
      dpi: 395,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "MagicOS 7.2",
      screen_size_inches: 6.78,
    },
    {
      name: "Honor X8b",
      dpi: 391,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "MagicOS 7.2",
      screen_size_inches: 6.7,
    },
    {
      name: "Honor X7b",
      dpi: 396,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 240,
      display_type: "IPS LCD",
      ui: "MagicOS 7.2",
      screen_size_inches: 6.8,
    },
    {
      name: "Otros Honor",
      dpi: 400,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 240,
      display_type: "OLED",
      ui: "MagicOS",
      screen_size_inches: 6.7,
    },
  ],
  motorola: [
    {
      name: "Edge 60 Ultra",
      dpi: 444,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 360,
      display_type: "P-OLED",
      ui: "MyUX",
      screen_size_inches: 6.7,
    },
    {
      name: "Edge 50 Ultra",
      dpi: 444,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 360,
      display_type: "P-OLED",
      ui: "MyUX",
      screen_size_inches: 6.7,
    },
    {
      name: "Edge 40 Pro",
      dpi: 395,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 360,
      display_type: "P-OLED",
      ui: "MyUX",
      screen_size_inches: 6.67,
    },
    {
      name: "Razr 50 Ultra",
      dpi: 413,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 360,
      display_type: "P-OLED",
      ui: "MyUX",
      screen_size_inches: 6.9,
    },
    {
      name: "Moto G85",
      dpi: 395,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 240,
      display_type: "P-OLED",
      ui: "MyUX",
      screen_size_inches: 6.7,
    },
    {
      name: "Moto G75",
      dpi: 395,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 240,
      display_type: "IPS LCD",
      ui: "MyUX",
      screen_size_inches: 6.7,
    },
    {
      name: "Moto G55",
      dpi: 395,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 240,
      display_type: "IPS LCD",
      ui: "MyUX",
      screen_size_inches: 6.5,
    },
    {
      name: "Moto G45",
      dpi: 269,
      tier: "low",
      hz: 60,
      touch_sampling_rate: 120,
      display_type: "IPS LCD",
      ui: "MyUX",
      screen_size_inches: 6.5,
    },
    {
      name: "Moto G24",
      dpi: 269,
      tier: "low",
      hz: 60,
      touch_sampling_rate: 120,
      display_type: "IPS LCD",
      ui: "MyUX",
      screen_size_inches: 6.6,
    },
    {
      name: "Moto E14",
      dpi: 270,
      tier: "low",
      hz: 60,
      touch_sampling_rate: 120,
      display_type: "IPS LCD",
      ui: "MyUX Go",
      screen_size_inches: 6.56,
    },
    {
      name: "Otros Motorola",
      dpi: 395,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 240,
      display_type: "IPS LCD",
      ui: "MyUX",
      screen_size_inches: 6.6,
    },
  ],
  oppo: [
    {
      name: "Find X8 Pro",
      dpi: 510,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "LTPO AMOLED",
      ui: "ColorOS",
      screen_size_inches: 6.82,
    },
    {
      name: "Find X7 Ultra",
      dpi: 510,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "LTPO AMOLED",
      ui: "ColorOS",
      screen_size_inches: 6.82,
    },
    {
      name: "Reno 12 Pro",
      dpi: 394,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "ColorOS",
      screen_size_inches: 6.7,
    },
    {
      name: "Reno 11 Pro",
      dpi: 394,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "ColorOS",
      screen_size_inches: 6.7,
    },
    {
      name: "Reno 10 Pro+",
      dpi: 450,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "ColorOS",
      screen_size_inches: 6.74,
    },
    {
      name: "Reno 8",
      dpi: 409,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "ColorOS",
      screen_size_inches: 6.43,
    },
    {
      name: "Oppo A80",
      dpi: 391,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "IPS LCD",
      ui: "ColorOS",
      screen_size_inches: 6.72,
    },
    {
      name: "Oppo A60",
      dpi: 391,
      tier: "low",
      hz: 60,
      touch_sampling_rate: 120,
      display_type: "IPS LCD",
      ui: "ColorOS",
      screen_size_inches: 6.67,
    },
    {
      name: "Otros Oppo",
      dpi: 400,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "AMOLED",
      ui: "ColorOS",
      screen_size_inches: 6.6,
    },
  ],
  realme: [
    {
      name: "GT 7 Pro",
      dpi: 450,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 360,
      display_type: "AMOLED",
      ui: "realme UI",
      screen_size_inches: 6.78,
    },
    {
      name: "GT 5 Pro",
      dpi: 450,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 360,
      display_type: "AMOLED",
      ui: "realme UI",
      screen_size_inches: 6.74,
    },
    {
      name: "Realme 13 Pro+",
      dpi: 450,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "realme UI",
      screen_size_inches: 6.7,
    },
    {
      name: "Realme 12 Pro+",
      dpi: 450,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "realme UI",
      screen_size_inches: 6.7,
    },
    {
      name: "Realme 11 Pro",
      dpi: 395,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "realme UI",
      screen_size_inches: 6.7,
    },
    {
      name: "Realme C67",
      dpi: 391,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "IPS LCD",
      ui: "realme UI",
      screen_size_inches: 6.72,
    },
    {
      name: "Realme C55",
      dpi: 269,
      tier: "low",
      hz: 60,
      touch_sampling_rate: 120,
      display_type: "IPS LCD",
      ui: "realme UI",
      screen_size_inches: 6.72,
    },
    {
      name: "Narzo 70 Turbo",
      dpi: 395,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "IPS LCD",
      ui: "realme UI",
      screen_size_inches: 6.72,
    },
    {
      name: "Narzo 60 Pro",
      dpi: 395,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "realme UI",
      screen_size_inches: 6.7,
    },
    {
      name: "Otros Realme",
      dpi: 400,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "IPS LCD",
      ui: "realme UI",
      screen_size_inches: 6.6,
    },
  ],
  oneplus: [
    {
      name: "OnePlus 13",
      dpi: 510,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 360,
      display_type: "LTPO AMOLED",
      ui: "OxygenOS",
      screen_size_inches: 6.82,
    },
    {
      name: "OnePlus 12",
      dpi: 510,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 360,
      display_type: "LTPO AMOLED",
      ui: "OxygenOS",
      screen_size_inches: 6.82,
    },
    {
      name: "OnePlus 11",
      dpi: 525,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 360,
      display_type: "LTPO AMOLED",
      ui: "OxygenOS",
      screen_size_inches: 6.7,
    },
    {
      name: "OnePlus 10 Pro",
      dpi: 525,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 360,
      display_type: "LTPO AMOLED",
      ui: "OxygenOS",
      screen_size_inches: 6.7,
    },
    {
      name: "OnePlus 9 Pro",
      dpi: 525,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 360,
      display_type: "LTPO AMOLED",
      ui: "OxygenOS",
      screen_size_inches: 6.7,
    },
    {
      name: "Nord 4",
      dpi: 394,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "OxygenOS",
      screen_size_inches: 6.74,
    },
    {
      name: "Nord CE 4",
      dpi: 394,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "OxygenOS",
      screen_size_inches: 6.7,
    },
    {
      name: "Otros OnePlus",
      dpi: 420,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "OxygenOS",
      screen_size_inches: 6.6,
    },
  ],
  vivo: [
    {
      name: "X200 Pro",
      dpi: 452,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 300,
      display_type: "LTPO AMOLED",
      ui: "Funtouch OS",
      screen_size_inches: 6.78,
    },
    {
      name: "X100 Pro",
      dpi: 452,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 300,
      display_type: "LTPO AMOLED",
      ui: "Funtouch OS",
      screen_size_inches: 6.78,
    },
    {
      name: "X90 Pro",
      dpi: 452,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "Funtouch OS",
      screen_size_inches: 6.78,
    },
    {
      name: "X Fold 3 Pro",
      dpi: 426,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "Funtouch OS",
      screen_size_inches: 8.0,
    },
    {
      name: "V40",
      dpi: 394,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "Funtouch OS",
      screen_size_inches: 6.78,
    },
    {
      name: "V30 Pro",
      dpi: 394,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "Funtouch OS",
      screen_size_inches: 6.78,
    },
    {
      name: "Y300 Pro",
      dpi: 391,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "IPS LCD",
      ui: "Funtouch OS",
      screen_size_inches: 6.72,
    },
    {
      name: "Y58",
      dpi: 391,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "IPS LCD",
      ui: "Funtouch OS",
      screen_size_inches: 6.72,
    },
    {
      name: "Otros Vivo",
      dpi: 400,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "IPS LCD",
      ui: "Funtouch OS",
      screen_size_inches: 6.6,
    },
  ],
  asus: [
    {
      name: "ROG Phone 9 Pro",
      dpi: 395,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 720,
      display_type: "AMOLED",
      ui: "ROG UI",
      screen_size_inches: 6.78,
    },
    {
      name: "ROG Phone 8 Pro",
      dpi: 395,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 720,
      display_type: "AMOLED",
      ui: "ROG UI",
      screen_size_inches: 6.78,
    },
    {
      name: "Zenfone 11 Ultra",
      dpi: 395,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "ZenUI",
      screen_size_inches: 6.78,
    },
    {
      name: "Zenfone 10",
      dpi: 445,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "ZenUI",
      screen_size_inches: 5.92,
    },
    {
      name: "Otros Asus",
      dpi: 400,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "ZenUI",
      screen_size_inches: 6.6,
    },
  ],
  google: [
    {
      name: "Pixel 9 Pro XL",
      dpi: 495,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "OLED",
      ui: "Pixel UI",
      screen_size_inches: 6.8,
    },
    {
      name: "Pixel 9",
      dpi: 422,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "OLED",
      ui: "Pixel UI",
      screen_size_inches: 6.1,
    },
    {
      name: "Pixel 8 Pro",
      dpi: 489,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "OLED",
      ui: "Pixel UI",
      screen_size_inches: 6.7,
    },
    {
      name: "Pixel 7 Pro",
      dpi: 512,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "OLED",
      ui: "Pixel UI",
      screen_size_inches: 6.7,
    },
    {
      name: "Otros Google",
      dpi: 450,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "OLED",
      ui: "Pixel UI",
      screen_size_inches: 6.5,
    },
  ],
  sony: [
    {
      name: "Xperia 1 VI",
      dpi: 643,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "OLED",
      ui: "Xperia UI",
      screen_size_inches: 6.5,
    },
    {
      name: "Xperia 5 VI",
      dpi: 449,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "OLED",
      ui: "Xperia UI",
      screen_size_inches: 6.1,
    },
    {
      name: "Xperia 10 VI",
      dpi: 457,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "OLED",
      ui: "Xperia UI",
      screen_size_inches: 6.1,
    },
    {
      name: "Otros Sony",
      dpi: 450,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "OLED",
      ui: "Xperia UI",
      screen_size_inches: 6.5,
    },
  ],
  nothing: [
    {
      name: "Nothing Phone (2a) Plus",
      dpi: 395,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 240,
      display_type: "OLED",
      ui: "Nothing OS",
      screen_size_inches: 6.7,
    },
    {
      name: "Nothing Phone (2)",
      dpi: 394,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "OLED",
      ui: "Nothing OS",
      screen_size_inches: 6.7,
    },
    {
      name: "Otros Nothing",
      dpi: 395,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "OLED",
      ui: "Nothing OS",
      screen_size_inches: 6.6,
    },
  ],
  tecno: [
    {
      name: "Phantom X2 Pro",
      dpi: 395,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "HiOS",
      screen_size_inches: 6.8,
    },
    {
      name: "Camon 30 Pro",
      dpi: 395,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "HiOS",
      screen_size_inches: 6.78,
    },
    {
      name: "Pova 6 Pro",
      dpi: 395,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "HiOS",
      screen_size_inches: 6.78,
    },
    {
      name: "Spark 20 Pro",
      dpi: 391,
      tier: "low",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "IPS LCD",
      ui: "HiOS",
      screen_size_inches: 6.78,
    },
    {
      name: "Otros Tecno",
      dpi: 390,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "IPS LCD",
      ui: "HiOS",
      screen_size_inches: 6.6,
    },
  ],
  infinix: [
    {
      name: "Zero 40",
      dpi: 395,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "XOS",
      screen_size_inches: 6.78,
    },
    {
      name: "Note 40 Pro",
      dpi: 395,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "XOS",
      screen_size_inches: 6.78,
    },
    {
      name: "Hot 50 Pro",
      dpi: 391,
      tier: "low",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "IPS LCD",
      ui: "XOS",
      screen_size_inches: 6.78,
    },
    {
      name: "Otros Infinix",
      dpi: 390,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "IPS LCD",
      ui: "XOS",
      screen_size_inches: 6.6,
    },
  ],
  zte: [
    {
      name: "Nubia Red Magic 10 Pro",
      dpi: 387,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 720,
      display_type: "AMOLED",
      ui: "Redmagic OS",
      screen_size_inches: 6.8,
    },
    {
      name: "Nubia Red Magic 9S Pro",
      dpi: 387,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 720,
      display_type: "AMOLED",
      ui: "Redmagic OS",
      screen_size_inches: 6.8,
    },
    {
      name: "Nubia Z60 Ultra",
      dpi: 400,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 360,
      display_type: "AMOLED",
      ui: "MyOS",
      screen_size_inches: 6.8,
    },
    {
      name: "Otros ZTE",
      dpi: 390,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 240,
      display_type: "AMOLED",
      ui: "MyOS",
      screen_size_inches: 6.6,
    },
  ],
  lg: [
    {
      name: "LG Velvet",
      dpi: 395,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "P-OLED",
      ui: "LG UX",
      screen_size_inches: 6.8,
    },
    {
      name: "LG V60 ThinQ",
      dpi: 395,
      tier: "high",
      hz: 60,
      touch_sampling_rate: 240,
      display_type: "P-OLED",
      ui: "LG UX",
      screen_size_inches: 6.8,
    },
    {
      name: "Otros LG",
      dpi: 390,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "OLED",
      ui: "LG UX",
      screen_size_inches: 6.4,
    },
  ],
  nokia: [
    {
      name: "XR21",
      dpi: 390,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "IPS LCD",
      ui: "Android One",
      screen_size_inches: 6.49,
    },
    {
      name: "G60",
      dpi: 395,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "IPS LCD",
      ui: "Android One",
      screen_size_inches: 6.58,
    },
    {
      name: "Otros Nokia",
      dpi: 380,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "IPS LCD",
      ui: "Android One",
      screen_size_inches: 6.5,
    },
  ],
  lenovo: [
    {
      name: "Legion Y90",
      dpi: 388,
      tier: "high",
      hz: 120,
      touch_sampling_rate: 720,
      display_type: "AMOLED",
      ui: "ZUI / Legion OS",
      screen_size_inches: 6.92,
    },
    {
      name: "Legion Pro",
      dpi: 395,
      tier: "high",
      hz: 144,
      touch_sampling_rate: 720,
      display_type: "AMOLED",
      ui: "ZUI / Legion OS",
      screen_size_inches: 6.65,
    },
    {
      name: "Otros Lenovo",
      dpi: 390,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 240,
      display_type: "IPS LCD",
      ui: "ZUI",
      screen_size_inches: 6.6,
    },
  ],
  otros: [
    {
      name: 'Android Genérico 6.5" 120 Hz',
      dpi: 400,
      tier: "mid",
      hz: 120,
      touch_sampling_rate: 240,
      display_type: "IPS/AMOLED",
      ui: "Genérico",
      screen_size_inches: 6.5,
    },
    {
      name: 'Android Genérico 6.5" 90 Hz',
      dpi: 400,
      tier: "mid",
      hz: 90,
      touch_sampling_rate: 180,
      display_type: "IPS/AMOLED",
      ui: "Genérico",
      screen_size_inches: 6.5,
    },
    {
      name: 'Android Genérico 6.5" 60 Hz',
      dpi: 400,
      tier: "low",
      hz: 60,
      touch_sampling_rate: 120,
      display_type: "IPS/AMOLED",
      ui: "Genérico",
      screen_size_inches: 6.5,
    },
    {
      name: 'Android Gama Baja 6.3" 60 Hz',
      dpi: 360,
      tier: "low",
      hz: 60,
      touch_sampling_rate: 120,
      display_type: "IPS",
      ui: "Genérico",
      screen_size_inches: 6.3,
    },
  ],
};

// ==========================================
// CÓDIGO DE REACT 19 Y LOGICA DEL CONTEXTO
// ==========================================

interface DeviceContextType {
  selectedBrand: DeviceBrand | null;
  selectedDevice: Device | null;
  setBrand: (brand: DeviceBrand | null) => void;
  setDevice: (device: Device | null) => void;
  getModelsByBrand: (brand: DeviceBrand) => Device[];
}

const DeviceContext = createContext<DeviceContextType | undefined>(undefined);

export function DeviceProvider({ children }: { children: React.ReactNode }) {
  const [selectedBrand, setBrand] = useState<DeviceBrand | null>(null);
  const [selectedDevice, setDevice] = useState<Device | null>(null);

  const getModelsByBrand = (brand: DeviceBrand) => RAW_DEVICES[brand] || [];

  const value = useMemo(
    () => ({
      selectedBrand,
      selectedDevice,
      setBrand: (brand: DeviceBrand | null) => {
        setBrand(brand);
        setDevice(null);
      },
      setDevice,
      getModelsByBrand,
    }),
    [selectedBrand, selectedDevice],
  );

  return (
    <DeviceContext.Provider value={value}>{children}</DeviceContext.Provider>
  );
}

export function useDevice() {
  const context = useContext(DeviceContext);
  if (!context)
    throw new Error("useDevice debe usarse dentro de un DeviceProvider");
  return context;
}
